version: "3.9"

services:
  client1:
    container_name: client-1
    build:
      context: ./gateway/gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway/gateway:/gateway/gateway
    working_dir: /gateway/gateway
    tty: true
    command: rebar3 shell
    ports:
      - "8080:8080"